
spring:
  profiles:
    active: local
server:
  port: 8080

---
spring:
  profiles: local
  datasource:
#    url: ${JDBC_URL}
    url:  jdbc:mysql://localhost:3306/cooks
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${JDBC_PASSWORD}
  mail:
    host: smtp.gmail.com
    username: akash.m.konnur.dummy@gmail.com
    password: Akash1234@
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

  jpa:
    hibernate.ddl-auto: update
    #properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect


